### ISSUE TITLE
Datenformat / Feld last_seen

### ISSUE THREAD

**Issue by yanosz** [FieldTracks/StoneAggregator#2]
Hallo,

mir ist gerade ein kleiner Unterschied im Datenformat aufgefallen - gibt's einen Hintergrund für den Unterschied?

Ist:
JellingStone: `"timestamp" : "2019-02-28T19:28:00Z"`
StoneAggregator: `"last_seen" : 1551382267`

Soll?: 
Möglichst ein einheitliches Datumsformat und Feldnamen verwenden (Vorschlag timestamp, ISO-Formartiert, da JSON-Date)

**Comment by yanosz** [comment]
Hi, könntest Du das Feld bitte bei Gelegenheit umstellen?

**Comment by yanosz** [comment]
... wobei eine Umbenennung in last_seen auch irgendwo passt, da das Feld eine andere Bedeutung hat.

Beim Datumsformat müssen wir etwas aufpassen, damit damit es keine Fehler gibt.

**Comment by henrikschnor** [comment]
Ich habe das Datum im StoneAggregator nun auf das gleiche Format vom JellingStone abgeändert, i.e. `"timestamp" : "2019-02-28T19:28:00Z"`.
