### ISSUE TITLE
Bug: Service terminiert nach MQTT-Verbindungsabbruch

### ISSUE THREAD

**Issue by yanosz** [FieldTracks/StoneAggregator#4]
Ist:
- Der Service terminiert, wenn die Verbindung zum MQTT-Broker abbricht - z.B. weil er neu gestartet wird.

Soll:
- Der Service verbindet sich erneut, sobald der MQTT-Broker zur Verfügung steht

**Comment by yanosz** [comment]
Könntest Du den Aggregator bitte anpassen? Idee: 1-3 reconnect nach 5 sekunden, 4-n reconnect nach jeweils 30 sekunden.

**Comment by henrikschnor** [comment]
Die reconect-Logik sollte nach dem letzten Commit nun etwas besser funktionieren. In meinen Tests hat sich der StoneAggregator nach Ausfall des MQTT-Servers neu verbunden und normal weitergearbeitet.

Falls das Problem trotzdem nochmal auftritt, mach das Issue einfach wieder auf.
