### ISSUE TITLE
MQTT "offline"

### ISSUE THREAD

**Issue by yanosz** [FieldTracks/StoneAggregator#6]
Ist:
* Im MQTT erscheinen keine Nachrichten
* Im Log fallen mir keine Fehler ins Auge

Soll: 
* Der MQTT-Broker sendet Nachrichten
* Probleme beim Senden oder Empfangen werden logged.

**Comment by yanosz** [comment]
Aufgetreten: 30.6. - 14:10

**Comment by henrikschnor** [comment]
Die reconect-Logik sollte nach dem letzten Commit nun etwas besser funktionieren. In meinen Tests hat sich der StoneAggregator nach Ausfall des MQTT-Servers neu verbunden und normal weitergearbeitet.

Falls das Problem trotzdem nochmal auftritt, mach das Issue einfach wieder auf.

**Comment by henrikschnor** [comment]
Bezieht sich das Problem auf den MQTT-Server selbst, oder ist es das Gleiche wie #4?

**Comment by henrikschnor** [comment]
Der Close-Button ist wirklich zu groß.

**Comment by yanosz** [comment]
Kein Ding :-).

Ich weiß nicht, ob es das gleiche Problem wie in #4 ist, da ich den Server nicht neu gestartet habe. Möglw. hängt #4 aber auch nicht mit dem Server-Neustart zusammen.

**Comment by yanosz** [comment]
Hmm.. mglw. wurde der MQTT-Server von ansible neu gestartet und es gibt einen Zussammenhang

Könntest Du bitte noch loggen, welcher Fehler konkret auftritt? Der Text gibt aktuell eher wenig Hinweise zum konkreten Problem.

**Comment by yanosz** [comment]
Sieht stabil aus - ich wäre für schließen ;)
